[package]
name = "services"
version = "0.1.0"
authors = ["Tom Panton <pantonshire@gmail.com>"]
edition = "2018"
description = "Load service information from services.yaml"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
